local:
  JWT_SECRET: 'local/jwt/secret'
  DDB_TABLE_USER: 'User'
  DDB_TABLE_SHOP: 'Shop'
prd:
  JWT_SECRET: 'prd/jwt/secret'
  DDB_TABLE_USER: 'Prd.User'
  DDB_TABLE_SHOP: 'Prd.Shop'
hml:
  JWT_SECRET: 'hml/jwt/secret'
  DDB_TABLE_USER: 'Hml.User'
  DDB_TABLE_SHOP: 'Hml.Shop'
